[tool.black]
exclude = '''
(
  /(
      \.git         # exclude a few common directories in the
    | \.direnv
    | \.venv
    | venv
  )/
)
'''

[tool.coverage.run]
branch = true
omit = [
  ".venv/*",
  "output_explorer/asgi.py",
  "output_explorer/settings.py",
  "output_explorer/wsgi.py",
  "services/sentry.py",
  "gateway/migrations/*",
  "reports/migrations/*",
  "manage.py",
]

[tool.coverage.report]
fail_under = 98
skip_covered = true

[tool.coverage.html]

[tool.isort]
profile = "black"
lines_after_imports = 2
skip_glob = [".direnv", "venv", ".venv"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "output_explorer.settings"
env = [
  "SECRET_KEY=12345",
  "REQUESTS_CACHE_NAME=test_cache",
  "DJANGO_VITE_DEV_MODE=True",
]
filterwarnings = [
    "ignore:distutils Version classes are deprecated:DeprecationWarning:marshmallow",
]
