# note: we do not run prod service with docker-compose, we use it just for
# configuring the production build
services:
  prod:
    # image name, both locally and public
    image: output-explorer
    build:
      context: ..
      # path relative to context
      dockerfile: docker/Dockerfile
      # the prod stage in the Dockerfile
      target: output-explorer-prod
      # should speed up the build in CI, where we have a cold cache
      cache_from:  # should speed up the build in CI, where we have a cold cache
        - ghcr.io/opensafely-core/base-docker
        - ghcr.io/opensafely-core/output-explorer
      args:
        # this makes the image work for later cache_from: usage
        - BUILDKIT_INLINE_CACHE=1
        # env vars supplied by just
        - BUILD_DATE
        - GITREF
    # use dockers builitin PID daemon
    init: true
    ports:
      - "8000:8000"

  # main development service
  dev:
    extends:
        service: prod
    image: output-explorer-dev
    container_name: output-explorer-dev
    # running as a specific uid/gid allows files written to mounted volumes by
    # the docker container's default user to match the host user's uid/gid, for
    # convienience.
    user: ${DOCKER_USERID:-1000}:${DOCKER_GROUPID:-1000}
    build:
      # the dev stage in the Dockerfile
      target: output-explorer-dev
      # pass the uid/gid as build arg
      args:
        - USERID=${DOCKER_USERID:-1000}
        - GROUPID=${DOCKER_GROUPID:-1000}
    # paths relative to docker-compose.yaml file
    env_file:
      - ../.env
    volumes:
      - ..:/app

  # test runner service - uses dev-image with a different commnd
  test:
    extends:
        service: dev
    container_name: output-explorer-test
    # override command
    command: /app/docker/entrypoints/test.sh
    # different default test env
    env_file:
      - ../.test.env
